/// Seasonal Japanese food pairings for each of the 72 kō.
///
/// The 72 micro-seasons grew up alongside the Japanese culinary calendar
/// (旬 shun — peak-season ingredients) and the wagashi tradition, in which
/// every confection is named for a flower, a bird, or a passing weather
/// pattern. The pairings here lean on those two threads:
///
/// 1. Where there is a famous wagashi or kyō-ryōri dish historically tied
///    to the sekki, that dish is used (e.g. sakura-mochi for cherry-bloom
///    season, hatsu-gatsuo for the early-summer bonito run, hange-shō for
///    Hange-shō, ozōni for New Year).
/// 2. Otherwise the dish is chosen from peak-of-shun ingredients of those
///    five days — the fish, vegetable, or fruit a Heian or Edo cook would
///    actually have on the cutting board.
library seasonal_foods;

/// Coarse food category — drives the icon shown on the row card.
enum FoodType {
  wagashi,    // 和菓子 traditional Japanese sweet
  sakana,     // 魚 fish, shellfish, sea life
  yasai,      // 野菜 vegetables, sansai, mountain greens
  gohan,      // ご飯 rice dishes (donburi, takikomi-gohan, sekihan)
  shirumono,  // 汁物 soup, nabe, miso-shiru
  men,        // 麺 noodles (soba, udon, sōmen, hiyamugi)
  hozon,      // 保存食 pickled, dried, fermented preserves
  nomimono,   // 飲み物 sake, amazake, special drink (not the tea)
  niku,       // 肉 meat, game, poultry, eggs
  kudamono,   // 果物 fruit
}

/// One seasonal Japanese dish paired to a single kō.
class FoodPairing {
  const FoodPairing({
    required this.japanese,
    required this.romaji,
    required this.nameUk,
    required this.nameEn,
    required this.type,
    required this.noteUk,
    required this.noteEn,
  });

  final String japanese;   // 桜餅, 鰹のたたき, etc.
  final String romaji;     // sakura-mochi, katsuo no tataki
  final String nameUk;     // Сакура-мочі (з гло[ссою])
  final String nameEn;     // Sakura mochi (with gloss)
  final FoodType type;
  final String noteUk;     // 1–2 quietly poetic sentences
  final String noteEn;     // English version
}

const Map<int, FoodPairing> seasonalFoods = {
  // ─── Spring ────────────────────────────────────────────────────────────
  1: FoodPairing(
    japanese: "恵方巻",
    romaji: "ehō-maki",
    nameUk: "Ехо-макі (товстий ролл удачі, з'їдений мовчки лицем до щасливого боку)",
    nameEn: "Ehō-maki (thick lucky roll, eaten in silence facing the year's auspicious direction)",
    type: FoodType.gohan,
    noteUk: "Товстий ролл сім начинок, з'їдений мовчки лицем до щасливого напрямку — останній подих Сецубуну, перш ніж східний вітер відімкне рік.",
    noteEn: "A thick seven-filling roll eaten in silence, facing the year's lucky direction — Setsubun's last breath before the east wind unlocks the year.",
  ),
  2: FoodPairing(
    japanese: "鶯餅",
    romaji: "uguisu-mochi",
    nameUk: "Угуїсу-мочі (зеленкуватий мочі у соєвому борошні, у формі солов'я)",
    nameEn: "Uguisu mochi (pale-green mochi dusted in roasted soy flour, shaped like a warbler)",
    type: FoodType.wagashi,
    noteUk: "Блідо-зелений мочі, посипаний кінако, у формі бамбукового солов'я — солодкий двійник пташки, що вперше пробує голос у горах.",
    noteEn: "A pale-green mochi shaped like a warbler and dusted with kinako — the sweet twin of the bird testing its first note in the hills.",
  ),
  3: FoodPairing(
    japanese: "白魚",
    romaji: "shirauo",
    nameUk: "Шіравуо (білі мальки-льодяки, ловлені під танучою кригою)",
    nameEn: "Shirauo (translucent icefish caught beneath the thawing ice)",
    type: FoodType.sakana,
    noteUk: "Прозорі білі мальки, які ще пахнуть талою кригою — їх ловлять малими сітями якраз тоді, коли річка вперше відкриває рот.",
    noteEn: "Translucent little fish that still smell of meltwater, scooped from the river the moment its mouth first opens.",
  ),
  4: FoodPairing(
    japanese: "草餅",
    romaji: "kusa-mochi",
    nameUk: "Куса-мочі (зелений мочі з полиновими паростками і червоною квасолею)",
    nameEn: "Kusa mochi (green yomogi mochi filled with sweet adzuki bean paste)",
    type: FoodType.wagashi,
    noteUk: "Травневий запах розтертого молодого полину в теплому рисі — той самий зелений, що проступає над зволоженою дощем землею.",
    noteEn: "The grassy scent of pounded young mugwort folded into warm rice — the same green that rises through soil the rain has just woken.",
  ),
  5: FoodPairing(
    japanese: "桜湯",
    romaji: "sakura-yu",
    nameUk: "Сакура-ю (настій соленої квітки сакури в окропі)",
    nameEn: "Sakura-yu (a single salt-pickled cherry blossom unfurling in hot water)",
    type: FoodType.nomimono,
    noteUk: "Одна солена квітка сакури, що повільно розкривається у чашці окропу — як та сама серпанкова смуга, що тримається над пагорбом.",
    noteEn: "One salt-pickled cherry blossom slowly opening in a cup of hot water — the same way mist begins to hold against a hillside.",
  ),
  6: FoodPairing(
    japanese: "ふきのとう天ぷら",
    romaji: "fukinotō tempura",
    nameUk: "Фукіното-темпура (бруньки білокопитника у легкому клярі)",
    nameEn: "Fukinotō tempura (butterbur buds in a light, lacy batter)",
    type: FoodType.yasai,
    noteUk: "Перші гіркуваті бруньки білокопитника у тонкому клярі — гіркота, що нагадує: рік ще тільки прокидається з-під снігу.",
    noteEn: "The first bitter butterbur buds in thin batter — a bitterness that reminds you the year has only just stirred from under the snow.",
  ),
  7: FoodPairing(
    japanese: "蕨のおひたし",
    romaji: "warabi no ohitashi",
    nameUk: "Варабі-но охітащі (молода папороть, ошпарена і полита соусом)",
    nameEn: "Warabi no ohitashi (young bracken fern, blanched and dressed in soy and dashi)",
    type: FoodType.yasai,
    noteUk: "Молода папороть, що тільки розкручує спіральки — її гіркота тверда, мов сонна комашка, що нарешті виповзла з-під каменя.",
    noteEn: "Young bracken still uncurling its fiddleheads — its taut bitterness like an insect easing out from under its stone.",
  ),
  8: FoodPairing(
    japanese: "菱餅",
    romaji: "hishi-mochi",
    nameUk: "Хіші-мочі (триколірний ромбоподібний мочі для свята дівчат)",
    nameEn: "Hishi mochi (three-tiered diamond rice cake for Hina-matsuri)",
    type: FoodType.wagashi,
    noteUk: "Трилисник із зеленого, білого і рожевого мочі — талий сніг, ще не зрушена земля і перший рум'янець персикового цвіту, складені в одну смужку.",
    noteEn: "A three-tier diamond of green, white, and pink mochi — melting snow, bare earth, and the first peach-blossom flush stacked in one slice.",
  ),
  9: FoodPairing(
    japanese: "菜の花のおひたし",
    romaji: "nanohana no ohitashi",
    nameUk: "Нанохана-но охітащі (квіти ріпаку, бланшовані з гірчицею)",
    nameEn: "Nanohana no ohitashi (rape blossoms blanched and dressed with mustard)",
    type: FoodType.yasai,
    noteUk: "Жовті квіти ріпаку, ошпарені й политі гірчицею — те саме поле, над яким щойно злетіли перші метелики.",
    noteEn: "Yellow rape blossoms blanched and dressed in mustard — the same field over which the first butterflies have only just risen.",
  ),
  10: FoodPairing(
    japanese: "雀寿司",
    romaji: "suzume-zushi",
    nameUk: "Судзуме-дзуші (маленькі суші у формі горобчика з морським лящем)",
    nameEn: "Suzume-zushi (small sparrow-shaped sushi of pickled sea bream over rice)",
    type: FoodType.sakana,
    noteUk: "Маленькі суші у формі горобчика з маринованим тай — крихкий пакуночок, як те перше гніздо в стрісі.",
    noteEn: "Tiny sushi shaped like a sparrow, sea bream draped over rice — neat as the first nest tucked under the eaves.",
  ),
  11: FoodPairing(
    japanese: "桜餅",
    romaji: "sakura-mochi",
    nameUk: "Сакура-мочі (рожевий рисовий пиріжок у солоному вишневому листку)",
    nameEn: "Sakura mochi (pink rice cake wrapped in a salt-pickled cherry leaf)",
    type: FoodType.wagashi,
    noteUk: "Рожевий пиріжок у солоному листку дикої вишні — солодке з ноткою морської солі, ехо саме того дня, коли в Кіото розкривається перша сакура.",
    noteEn: "A pink rice cake folded in a salt-pickled wild cherry leaf — the sweet-and-saline echo of the very day Kyoto's first sakura opens.",
  ),
  12: FoodPairing(
    japanese: "蛤のお吸い物",
    romaji: "hamaguri no osuimono",
    nameUk: "Хамагурі-но осуімоно (чистий бульйон з молюсками-серцівками)",
    nameEn: "Hamaguri no osuimono (clear broth with hard-shell clams)",
    type: FoodType.shirumono,
    noteUk: "Прозорий бульйон з відкритими стулками молюсків — глухий, далекий гул, наче перший березневий грім за горою.",
    noteEn: "A clear broth in which clam shells slowly part — a low, far-off rumble, like March's first thunder behind the hill.",
  ),
  13: FoodPairing(
    japanese: "筍ご飯",
    romaji: "takenoko-gohan",
    nameUk: "Такеноко-ґохан (рис, варений з молодими паростками бамбука)",
    nameEn: "Takenoko gohan (rice steamed with fresh bamboo shoots)",
    type: FoodType.gohan,
    noteUk: "Рис, що увібрав солодку землистість молодого бамбука, які розгортають листки якраз тоді, коли під ними шугають перші ластівки.",
    noteEn: "Rice that has drunk the sweet, earthy juice of new bamboo — pushing up just as the first swallows skim back over the field.",
  ),
  14: FoodPairing(
    japanese: "山菜の天ぷら",
    romaji: "sansai tempura",
    nameUk: "Сансай-темпура (темпура з гірських трав і паростків)",
    nameEn: "Sansai tempura (mountain greens and shoots in light tempura)",
    type: FoodType.yasai,
    noteUk: "Гіркуваті гірські трави в легкому клярі — здається, наче на язик опустилась тінь стрункого клина гусей, що тягнуться на північ.",
    noteEn: "Bitter mountain greens in lacy batter — as if the shadow of a northbound goose-skein had settled briefly on the tongue.",
  ),
  15: FoodPairing(
    japanese: "苺大福",
    romaji: "ichigo-daifuku",
    nameUk: "Ічіґо-дайфуку (мочі з цілою полуницею в білій квасолевій пасті)",
    nameEn: "Ichigo daifuku (whole strawberry wrapped in white bean paste and mochi)",
    type: FoodType.wagashi,
    noteUk: "Біла мочі, біла квасоля, червоне сонце полуниці посередині — маленька веселка під шкіркою, тільки перевернута.",
    noteEn: "White mochi, white bean paste, a red strawberry sun in the middle — a small rainbow tucked under skin, only rearranged.",
  ),
  16: FoodPairing(
    japanese: "若竹煮",
    romaji: "wakatake-ni",
    nameUk: "Вакатаке-ні (тушковані бамбук та вакаме у легкому даші)",
    nameEn: "Wakatake-ni (bamboo shoots and wakame seaweed simmered in dashi)",
    type: FoodType.yasai,
    noteUk: "Молодий бамбук і весняна вакаме в одному горщику — те, що проростає з землі, і те, що з моря, зустрічаються в чистому даші.",
    noteEn: "Young bamboo and spring wakame meeting in one pot — what comes up from the soil and what comes up from the sea, joined in clear dashi.",
  ),
  17: FoodPairing(
    japanese: "赤飯",
    romaji: "sekihan",
    nameUk: "Секіхан (святковий клейкий рис із червоною квасолею)",
    nameEn: "Sekihan (festive sticky rice steamed with adzuki beans)",
    type: FoodType.gohan,
    noteUk: "Клейкий рис, рожево забарвлений соком адзукі — святкова страва на знак того, що останній іній зійшов і молоде рисове поле починає зеленіти.",
    noteEn: "Sticky rice tinted pink by adzuki juice — a quiet celebration that the last frost has lifted and the seedling beds begin to green.",
  ),
  18: FoodPairing(
    japanese: "柏餅",
    romaji: "kashiwa-mochi",
    nameUk: "Кашіва-мочі (мочі з квасолевою пастою у дубовому листі для свята хлопчиків)",
    nameEn: "Kashiwa mochi (sweet mochi wrapped in an oak leaf for Boys' Day)",
    type: FoodType.wagashi,
    noteUk: "Білий мочі, обгорнутий у твердий лист дуба — піон вже відцвів, але міцність кореня лишається на язиці гіркуватим запахом дерева.",
    noteEn: "White mochi folded in a stiff oak leaf — the peony has bloomed and gone, but the rooted strength stays as a faint woody bitterness.",
  ),
  // ─── Summer ────────────────────────────────────────────────────────────
  19: FoodPairing(
    japanese: "粽",
    romaji: "chimaki",
    nameUk: "Чімакі (довгаста рисова галушка у бамбуковому листку, на День хлопчиків)",
    nameEn: "Chimaki (long sweet rice dumpling wrapped in bamboo leaf, eaten on Tango-no-sekku)",
    type: FoodType.wagashi,
    noteUk: "Довгаста рисова галушка у бамбуковому листі — той самий зелений запах болота, з якого тільки-но почали озиватися перші жаби.",
    noteEn: "A long rice dumpling wrapped in bamboo leaf — the same green marsh smell from which the first frogs are just beginning to call.",
  ),
  20: FoodPairing(
    japanese: "新茶",
    romaji: "shincha",
    nameUk: "Шінча (перший збір зеленого чаю року, восьмого-десятого травня)",
    nameEn: "Shincha (the year's first-flush green tea, picked around the eighty-eighth night)",
    type: FoodType.nomimono,
    noteUk: "Перший збір року — листя, зрізане в день, коли земля волога й дощові черв'яки виповзають назовні; смак трави, що ще не знала спеки.",
    noteEn: "The first leaves of the year, plucked the same week earthworms surface — the taste of grass that has not yet known heat.",
  ),
  21: FoodPairing(
    japanese: "若竹汁",
    romaji: "wakatake-jiru",
    nameUk: "Вакатаке-джіру (прозорий суп з молодим бамбуком і вакаме)",
    nameEn: "Wakatake-jiru (clear soup of young bamboo shoots and wakame)",
    type: FoodType.shirumono,
    noteUk: "Чистий бульйон, у якому плаває молодий бамбук — той самий пагін, що пройшов крізь землю всього за п'ять травневих днів.",
    noteEn: "Clear broth holding fresh bamboo shoots — the same spear that has driven up through the earth in just five May days.",
  ),
  22: FoodPairing(
    japanese: "桑の実ジャム",
    romaji: "kuwa no mi jam",
    nameUk: "Кува-но мі джем (варення з ягід шовковиці)",
    nameEn: "Kuwa no mi jam (mulberry preserve, ladled over fresh tofu or curd)",
    type: FoodType.hozon,
    noteUk: "Темно-фіолетове варення з шовковиці — листя того ж дерева щодня годує шовкопрядів, а ягоди залишаються на варення для нас.",
    noteEn: "A dark mulberry preserve — silkworms eat the same tree's leaves all day, while the berries are left to thicken for us.",
  ),
  23: FoodPairing(
    japanese: "紅花蕎麦",
    romaji: "benibana soba",
    nameUk: "Бенібана-соба (гречана локшина, фарбована шафрановими квітами)",
    nameEn: "Benibana soba (buckwheat noodles tinted gold by safflower)",
    type: FoodType.men,
    noteUk: "Гречана локшина в жовто-помаранчевому бульйоні — той самий колір, що зараз заливає поля шафрану в Ямаґаті.",
    noteEn: "Buckwheat noodles in a broth coloured a yellow-orange — the very colour now flooding the safflower fields of Yamagata.",
  ),
  24: FoodPairing(
    japanese: "水無月",
    romaji: "minazuki",
    nameUk: "Мінадзукі (трикутний уйро з адзукі для очищення від літніх хвороб)",
    nameEn: "Minazuki (triangular uirō topped with adzuki, eaten on June 30 to ward off summer ills)",
    type: FoodType.wagashi,
    noteUk: "Білий тремтливий трикутник, посипаний адзукі — як стесаний кутик льодовика, привезеного колись із гір до палацу серед літа.",
    noteEn: "A trembling white triangle dotted with adzuki — like a sliver of mountain ice once carried down to the summer palace.",
  ),
  25: FoodPairing(
    japanese: "鯵の南蛮漬け",
    romaji: "aji no nanban-zuke",
    nameUk: "Аджі-но намбан-дзуке (смажений ставрид у солодко-кислому соусі з перцем)",
    nameEn: "Aji no nanban-zuke (fried horse mackerel marinated in sweet-sour pepper vinegar)",
    type: FoodType.sakana,
    noteUk: "Смажений ставрид у легкому оцті з перцем — гострий, чіпкий смак, як передні лапи богомола, що щойно вилупився серед липкого літа.",
    noteEn: "Fried horse mackerel in vinegar with chili — a sharp, gripping taste, like a newly hatched mantis testing its forelegs in the heat.",
  ),
  26: FoodPairing(
    japanese: "若鮎の塩焼き",
    romaji: "wakaayu shio-yaki",
    nameUk: "Вакаю шіо-які (молодий аю з гірської річки, на грилі з сіллю)",
    nameEn: "Wakaayu shio-yaki (young sweetfish skewered and salt-grilled, eaten whole)",
    type: FoodType.sakana,
    noteUk: "Молодий аю на шпажці, посипаний сіллю — у його річці зараз спалахують перші світляки, наче з-під каменів зривається тиха електрика.",
    noteEn: "Young ayu skewered and salt-grilled — the same river where, after dusk, fireflies begin lifting like a soft electricity off the stones.",
  ),
  27: FoodPairing(
    japanese: "梅干し",
    romaji: "umeboshi",
    nameUk: "Умебоші (солені сушені сливи, вижовклі на сонці)",
    nameEn: "Umeboshi (sun-dried, salt-pickled plums)",
    type: FoodType.hozon,
    noteUk: "Жовто-руда зморщена слива, висушена на трьох літніх сонцях — той самий плід, що зараз дозріває до медового кольору на гілці.",
    noteEn: "A wrinkled, ochre plum dried under three summer suns — the same fruit now ripening to honey-colour on the branch.",
  ),
  28: FoodPairing(
    japanese: "夏野菜の冷やし鉢",
    romaji: "natsu-yasai no hiyashi-bachi",
    nameUk: "Нацу-ясай-но хіяші-бачі (літні овочі, охолоджені у даші)",
    nameEn: "Natsu-yasai no hiyashi-bachi (summer vegetables chilled in dashi)",
    type: FoodType.yasai,
    noteUk: "Холодна миска з томатом, баклажаном і миога-імбиром, що плавають у даші — крихкий притулок проти полудневого сонця.",
    noteEn: "A cold bowl of tomato, eggplant and myōga ginger floating in dashi — a thin shelter held against the high-noon sun.",
  ),
  29: FoodPairing(
    japanese: "鱧の落とし",
    romaji: "hamo no otoshi",
    nameUk: "Хамо-но отоші (морський вугор, відварений шматочками і поданий з умебоші)",
    nameEn: "Hamo no otoshi (pike conger blanched in petal-like slices, served with plum sauce)",
    type: FoodType.sakana,
    noteUk: "Білі пелюстки морського вугра, що розкриваються у крижаній воді — ірис, який також зараз розпускається біля кіотських ставків.",
    noteEn: "White petals of pike conger opening in iced water — the same shape as the iris now lifting beside Kyoto's ponds.",
  ),
  30: FoodPairing(
    japanese: "蛸",
    romaji: "tako",
    nameUk: "Тако (восьминіг, з'їдений на Хан-ґе щоб рис кріпко вкорінився)",
    nameEn: "Tako (octopus eaten on Hange-shō so that rice will root deep)",
    type: FoodType.sakana,
    noteUk: "У Кансаї на Хан-ґе їдять восьминога, щоб його присоски передали рисові своє чіпке коріння — селянська магія, прихована у звичайному обіді.",
    noteEn: "In Kansai, on Hange-shō, octopus is eaten so its suction-cups pass their grip to the rice — a farmer's spell hidden in plain lunch.",
  ),
  31: FoodPairing(
    japanese: "素麺",
    romaji: "sōmen",
    nameUk: "Сомен (тонка пшенична локшина, охолоджена у крижаній воді на Танабату)",
    nameEn: "Sōmen (fine wheat noodles chilled in iced water for Tanabata)",
    type: FoodType.men,
    noteUk: "Тонка біла нитка локшини у крижаній воді — як та сама зоряна стрічка, яку Орігіме і Хіко-боші перекидають один одному раз на рік.",
    noteEn: "A thin white thread of noodle in iced water — like the strand of stars Orihime and Hikoboshi reach across to each other once a year.",
  ),
  32: FoodPairing(
    japanese: "水羊羹",
    romaji: "mizu-yōkan",
    nameUk: "Мідзу-йокан (охолоджене желе з адзукі)",
    nameEn: "Mizu-yōkan (chilled, lightly-set adzuki bean jelly)",
    type: FoodType.wagashi,
    noteUk: "Холодне темно-червоне желе з адзукі, нарізане квадратом — рівне і прозоре, як ставок, на якому щойно розкрилася перша лотосова квітка.",
    noteEn: "A cool, dark-red adzuki jelly cut square — flat and clear as the pond on which the first lotus has only just opened.",
  ),
  33: FoodPairing(
    japanese: "鰻の白焼き",
    romaji: "unagi no shiroyaki",
    nameUk: "Унаґі-но шіро-які (білий вугор без соусу, гриль зі солями)",
    nameEn: "Unagi no shiroyaki (eel grilled plain over charcoal, served with salt and wasabi)",
    type: FoodType.sakana,
    noteUk: "Білий вугор без солодкого соусу, тільки сіль і вугільний дим — зосереджена сила, як яструб, що ще тільки вчиться розправляти крила.",
    noteEn: "Eel grilled plain over charcoal, only salt and smoke — a concentrated strength, like a young hawk first learning the shape of its wing.",
  ),
  34: FoodPairing(
    japanese: "葛切り",
    romaji: "kuzukiri",
    nameUk: "Кудзу-кірі (прозора крохмальна локшина з кудзу, в чорному цукровому сиропі)",
    nameEn: "Kuzukiri (translucent kudzu starch noodles served in dark sugar syrup)",
    type: FoodType.wagashi,
    noteUk: "Прозорі скляні стрічки кудзу в темному цукрі куроміцу — холодне, що ковзає горлом, поки за вікном павловнія в'яже зернятка.",
    noteEn: "Translucent kudzu ribbons in dark kuromitsu syrup — a cool, slippery sweetness while the paulownia outside is knotting its seeds.",
  ),
  35: FoodPairing(
    japanese: "冷奴",
    romaji: "hiyayakko",
    nameUk: "Хіяякко (холодний тофу з імбиром, цибулею і соєвим соусом)",
    nameEn: "Hiyayakko (cold silken tofu topped with ginger, scallion, and soy)",
    type: FoodType.yasai,
    noteUk: "Холодна біла цеглинка тофу під ложкою тертого імбиру — мала прохолода, яку вистачає на найгустішу, найпарнішу годину дня.",
    noteEn: "A cold white slab of silken tofu under a spoon of grated ginger — a small coolness, just enough for the day's heaviest, dampest hour.",
  ),
  36: FoodPairing(
    japanese: "鰻丼",
    romaji: "unadon",
    nameUk: "Унадон (рис із зацукрованим вугрем, страва Дойо-но-уші у спеку)",
    nameEn: "Unadon (rice topped with kabayaki eel, eaten on Doyō no Ushi)",
    type: FoodType.gohan,
    noteUk: "Засмаглий вугор у солодкому соусі поверх гарячого рису — їжа дня великих злив, коли тіло змивають літні води, а сила потрібна знов.",
    noteEn: "Lacquered eel over hot rice — the food of cloudburst days, when summer's water washes the body and one's strength must be replaced.",
  ),
  // ─── Autumn ────────────────────────────────────────────────────────────
  37: FoodPairing(
    japanese: "枝豆",
    romaji: "edamame",
    nameUk: "Едамаме (молода соя у стручках, відварена з сіллю)",
    nameEn: "Edamame (young soybeans in their pods, boiled in salted water)",
    type: FoodType.yasai,
    noteUk: "Молода соя у стручку, ще тепла від солоної води — простий смак, що добре йде з першим прохолодним вітром з-за дому.",
    noteEn: "Young soybeans in the pod, still warm from salted water — a plain taste matched to the first cool wind slipping past the house.",
  ),
  38: FoodPairing(
    japanese: "茄子の田楽",
    romaji: "nasu no dengaku",
    nameUk: "Насу-но денґаку (баклажан, гриль з солодким місо)",
    nameEn: "Nasu no dengaku (grilled eggplant glazed with sweet miso)",
    type: FoodType.yasai,
    noteUk: "Темний баклажан під шаром солодкого місо — м'якоть, що тане, поки за стіною звечора співає одна-єдина хіґураші.",
    noteEn: "A dark eggplant under a slow layer of sweet miso — flesh dissolving while a single evening cicada sings beyond the wall.",
  ),
  39: FoodPairing(
    japanese: "きのこ蕎麦",
    romaji: "kinoko soba",
    nameUk: "Кіноко-соба (гречана локшина у бульйоні з осінніми грибами)",
    nameEn: "Kinoko soba (buckwheat noodles in a broth of mixed autumn mushrooms)",
    type: FoodType.men,
    noteUk: "Гречана локшина у темному бульйоні з осінніх грибів — гарячий, землистий запах підіймається парою, як той туман, що сідає над долиною.",
    noteEn: "Buckwheat noodles in dark broth of autumn mushrooms — a warm, earthy steam rising like the thick fog now settling in the valley.",
  ),
  40: FoodPairing(
    japanese: "無花果の白和え",
    romaji: "ichijiku no shira-ae",
    nameUk: "Ічідзіку-но шіра-ае (інжир у тофу-кунжутному соусі)",
    nameEn: "Ichijiku no shira-ae (figs dressed in mashed tofu and white sesame)",
    type: FoodType.kudamono,
    noteUk: "Стиглий інжир, прим'ятий з тофу й білим кунжутом — м'яка біла подушка, що нагадує перші бавовняні квіти, що розкриваються в полі.",
    noteEn: "Ripe figs folded into mashed tofu and white sesame — a soft white cushion echoing the first cotton blossoms opening in the field.",
  ),
  41: FoodPairing(
    japanese: "桃",
    romaji: "momo",
    nameUk: "Момо (соковитий персик пізнього серпня)",
    nameEn: "Momo (a ripe late-summer peach, peeled and eaten chilled)",
    type: FoodType.kudamono,
    noteUk: "Соковитий персик з останнього теплого тижня — солодкий і трохи стомлений, як день, у якому спека нарешті починає відступати.",
    noteEn: "A ripe peach from the last warm week — sweet and a little weary, like a day in which the heat is finally beginning to step back.",
  ),
  42: FoodPairing(
    japanese: "新米",
    romaji: "shinmai",
    nameUk: "Шінмай (перший рис нового врожаю, варений на пару)",
    nameEn: "Shinmai (the year's first new rice, simply steamed)",
    type: FoodType.gohan,
    noteUk: "Перший рис цього року, тільки обварений — він пахне молоком і свіжою травою, бо його зерно лише вчора було молодим колоском.",
    noteEn: "This year's first rice, plainly steamed — it smells of milk and new grass, because its grains were green ears only yesterday.",
  ),
  43: FoodPairing(
    japanese: "さつまいもご飯",
    romaji: "satsumaimo gohan",
    nameUk: "Сацумаімо-ґохан (рис, варений зі шматочками батату)",
    nameEn: "Satsumaimo gohan (rice steamed with chunks of sweet potato)",
    type: FoodType.gohan,
    noteUk: "Рис, у якому ховаються жовті шматочки батату — той самий жовтий, що блищить уранці на травинках, перш ніж роса висохне.",
    noteEn: "Rice hiding yellow pieces of sweet potato — the same yellow that catches in the morning grass before the white dew dries.",
  ),
  44: FoodPairing(
    japanese: "秋刀魚の塩焼き",
    romaji: "sanma no shio-yaki",
    nameUk: "Санма-но шіо-які (тихоокеанський бичок, гриль з сіллю і дайконом)",
    nameEn: "Sanma no shio-yaki (Pacific saury salt-grilled with grated daikon)",
    type: FoodType.sakana,
    noteUk: "Срібляста риба під сіллю і над вугіллям — на іншому березі річки в цей час трясогузка вистукує дзьобом по гальці.",
    noteEn: "A silver fish salted and laid over coals — on the river-stone, just then, a wagtail is tapping its beak in time with the grill.",
  ),
  45: FoodPairing(
    japanese: "栗きんとん",
    romaji: "kuri-kinton",
    nameUk: "Курі-кінтон (солодке пюре з варених каштанів)",
    nameEn: "Kuri-kinton (sweet purée of steamed chestnuts, formed by hand)",
    type: FoodType.wagashi,
    noteUk: "Жовте пюре з каштанів, скручене серветкою у краплинку — невеликий вузлик солодкої осені у долоні, поки ластівки летять на південь.",
    noteEn: "Yellow chestnut purée twisted in a cloth into a teardrop — a small knot of sweet autumn in the palm as the swallows go south.",
  ),
  46: FoodPairing(
    japanese: "おはぎ",
    romaji: "ohagi",
    nameUk: "Охаґі (рисова кулька, обкачана у солодкій пасті адзукі, на Хіган)",
    nameEn: "Ohagi (rice ball coated in sweet adzuki paste, eaten at Higan)",
    type: FoodType.wagashi,
    noteUk: "Рисова кулька в темно-червоній пасті адзукі — дар, який лишають на родинному вівтарі у дні рівнодення, коли вже стихає грім.",
    noteEn: "A rice ball wrapped in dark adzuki paste — an offering laid on the family altar at the equinox, after thunder has finally hushed.",
  ),
  47: FoodPairing(
    japanese: "里芋の煮物",
    romaji: "satoimo no nimono",
    nameUk: "Сатоімо-но німоно (тушковані бульби таро у соєвому даші)",
    nameEn: "Satoimo no nimono (taro corms simmered slowly in soy and dashi)",
    type: FoodType.yasai,
    noteUk: "Тушковані бульби таро в темному даші — землиста, заспокійлива страва на той вечір, коли всяка дрібна комашка зникає під дерниною.",
    noteEn: "Taro corms simmered in dark dashi — a settling, earthen dish for the evening when every small insect tucks itself back under the soil.",
  ),
  48: FoodPairing(
    japanese: "新蕎麦",
    romaji: "shin-soba",
    nameUk: "Шін-соба (нова гречана локшина з осіннього збору)",
    nameEn: "Shin-soba (the season's first new buckwheat noodles)",
    type: FoodType.men,
    noteUk: "Нова гречана локшина з осіннього збору — її зеленкуватий запах долетів від щойно осушеного поля, з якого селянин відвів воду.",
    noteEn: "Fresh buckwheat noodles, just-milled — their faint green scent drifting from the very field the farmer has only now drained dry.",
  ),
  49: FoodPairing(
    japanese: "鴨鍋",
    romaji: "kamo-nabe",
    nameUk: "Камо-набе (гарячий горщик з качкою, цибулею-пореєм та грибами)",
    nameEn: "Kamo-nabe (hot pot of wild duck, leek, and mushrooms)",
    type: FoodType.niku,
    noteUk: "Гарячий горщик із качкою і цибулею-пореєм — сезон диких гусей знову відкрився, бульйон темнішає сам собою з кожною хвилиною.",
    noteEn: "A hot pot of wild duck and naga-negi leek — the season of returning geese is open again, the broth darkening minute by minute.",
  ),
  50: FoodPairing(
    japanese: "菊酒",
    romaji: "kiku-zake",
    nameUk: "Кіку-дзаке (саке з пелюсткою хризантеми, на свято Чойо)",
    nameEn: "Kiku-zake (sake floated with a chrysanthemum petal for Chōyō no Sekku)",
    type: FoodType.nomimono,
    noteUk: "Тепле саке з однією жовтою пелюсткою хризантеми — дев'ятий день дев'ятого місяця, коли пелюстка нібито додає сім років життя.",
    noteEn: "Warm sake with a single yellow chrysanthemum petal afloat — on the ninth day of the ninth month, said to add seven years of life.",
  ),
  51: FoodPairing(
    japanese: "里芋汁",
    romaji: "satoimo-jiru",
    nameUk: "Сатоімо-джіру (місо-суп з таро і коренеплодами)",
    nameEn: "Satoimo-jiru (miso soup with taro, carrot and burdock root)",
    type: FoodType.shirumono,
    noteUk: "Гарячий місо-суп з таро, морквою і ґобо — їдять близько порога саме тоді, коли цвіркун уже сидить біля самих дверей.",
    noteEn: "Warm miso soup with taro, carrot and burdock — eaten close to the door, just as the cricket has settled by that same threshold.",
  ),
  52: FoodPairing(
    japanese: "柿",
    romaji: "kaki",
    nameUk: "Какі (стигла хурма пізньої осені)",
    nameEn: "Kaki (a late-autumn persimmon, peeled at the kitchen table)",
    type: FoodType.kudamono,
    noteUk: "Помаранчева хурма, очищена ножем над тарілкою — її холодна, медова м'якоть зустрічає першу солодкаву нотку інею в ранковому повітрі.",
    noteEn: "An orange persimmon peeled at the table — its cool, honeyed flesh meeting the first whiff of frost in the morning air.",
  ),
  53: FoodPairing(
    japanese: "きのこ汁",
    romaji: "kinoko-jiru",
    nameUk: "Кіноко-джіру (місо-суп з лісовими грибами)",
    nameEn: "Kinoko-jiru (miso soup with mixed forest mushrooms)",
    type: FoodType.shirumono,
    noteUk: "Темний місо-суп з мацутаке, шіймеджі і шіїтаке — пара з місочки густішає у вечірньому повітрі, як короткі дощики, що пройдуть і затихнуть.",
    noteEn: "A dark miso soup of matsutake, shimeji and shiitake — its steam thickening in the evening air, like the brief rain showers passing through.",
  ),
  54: FoodPairing(
    japanese: "栗ご飯",
    romaji: "kuri-gohan",
    nameUk: "Курі-ґохан (рис, варений з очищеними каштанами)",
    nameEn: "Kuri gohan (rice steamed with peeled chestnuts)",
    type: FoodType.gohan,
    noteUk: "Білий рис, у якому світяться золоті половинки каштанів — той самий колір, що щойно охопив клени і плющ на схилі.",
    noteEn: "White rice glowing with golden halves of chestnut — the same colour that has just taken hold of the maple and the climbing ivy.",
  ),
  // ─── Winter ────────────────────────────────────────────────────────────
  55: FoodPairing(
    japanese: "椿餅",
    romaji: "tsubaki-mochi",
    nameUk: "Цубакі-мочі (мочі з адзукі між двома листками камелії)",
    nameEn: "Tsubaki mochi (mochi with adzuki paste, pressed between two camellia leaves)",
    type: FoodType.wagashi,
    noteUk: "Білий мочі з адзукі, зажатий між двома темно-зеленими листками камелії — найдавніша солодка вагаші Японії, ще з часів Хейан.",
    noteEn: "White mochi with adzuki pressed between two dark camellia leaves — Japan's oldest recorded wagashi, eaten since the Heian court.",
  ),
  56: FoodPairing(
    japanese: "湯豆腐",
    romaji: "yu-dōfu",
    nameUk: "Ю-доофу (тофу, повільно томлений у бульйоні з комбу)",
    nameEn: "Yu-dōfu (silken tofu simmered slowly in a kombu broth)",
    type: FoodType.shirumono,
    noteUk: "Біла цеглинка тофу повільно нагрівається в комбу-даші — пара заволікає миску, поки за дверима земля починає вперше тверднути від холоду.",
    noteEn: "A block of silken tofu warming slowly in kombu broth — steam thickens over the bowl as the soil outside first hardens with cold.",
  ),
  57: FoodPairing(
    japanese: "蕪蒸し",
    romaji: "kabura-mushi",
    nameUk: "Кабура-муші (тушкована ріпа з білою рибою у прозорому соусі)",
    nameEn: "Kabura-mushi (steamed grated turnip over white fish, in clear sauce)",
    type: FoodType.yasai,
    noteUk: "Подрібнена біла ріпа, парена над рибою, під прозорим соусом куздзу — м'яка, як перший нарцис, що вже відкрив один-єдиний дзвоник.",
    noteEn: "Grated white turnip steamed over fish under a clear kuzu sauce — soft as the first daffodil that has only just opened one bell.",
  ),
  58: FoodPairing(
    japanese: "鰤大根",
    romaji: "buri-daikon",
    nameUk: "Бурі-дайкон (зимова жовтохвіста риба, тушкована з дайконом у соєвому соусі)",
    nameEn: "Buri-daikon (winter yellowtail simmered with daikon in soy and ginger)",
    type: FoodType.sakana,
    noteUk: "Жовтохвіст і дайкон у спільному соєвому горщику — рибка вже жирна на холоді, а веселка тим часом ховається на цілих півроку.",
    noteEn: "Yellowtail and daikon in one soy-ginger pot — the fish has gone fat in the cold, while the rainbow has hidden for half a year.",
  ),
  59: FoodPairing(
    japanese: "けんちん汁",
    romaji: "kenchin-jiru",
    nameUk: "Кенчін-джіру (овочевий суп з тофу і коренеплодами)",
    nameEn: "Kenchin-jiru (vegetable soup with crumbled tofu, daikon, carrot and burdock)",
    type: FoodType.shirumono,
    noteUk: "Овочевий суп з кореневищами і подрібненим тофу — гарячий вітер з горщика стоїть проти північного вітру, що зриває останнє листя з гілок.",
    noteEn: "A root-vegetable soup with crumbled tofu — its warm pot-wind stands against the north wind tearing the last leaves from their branches.",
  ),
  60: FoodPairing(
    japanese: "おでん",
    romaji: "oden",
    nameUk: "Оден (зимовий тушений набір у даші — дайкон, яйце, конняку)",
    nameEn: "Oden (a winter simmer of daikon, egg, konjac and fish cake in dashi)",
    type: FoodType.shirumono,
    noteUk: "Велика каструля одену з дайконом, яйцем і чікува у золотистому даші — зимовий вечір, який пахне, як дозрілий татабана на гілці.",
    noteEn: "A wide pot of oden — daikon, egg and chikuwa in gold dashi — a winter evening with the scent of ripening tachibana on the branch.",
  ),
  61: FoodPairing(
    japanese: "粕汁",
    romaji: "kasu-jiru",
    nameUk: "Касу-джіру (суп з саке-касу, лосося і коренеплодів)",
    nameEn: "Kasu-jiru (soup of sake lees, salmon and root vegetables)",
    type: FoodType.shirumono,
    noteUk: "Молочно-біла місочка з саке-касу, лососем і коренеплодами — її пара перша зустрічає холод, що тепер усідається в кожному кутку дому.",
    noteEn: "A milky bowl of sake lees, salmon and roots — its steam the first thing to meet the cold now settling into every corner of the house.",
  ),
  62: FoodPairing(
    japanese: "牡丹鍋",
    romaji: "botan-nabe",
    nameUk: "Ботан-набе (гарячий горщик з диким кабаном, викладеним у формі піонії)",
    nameEn: "Botan-nabe (hot pot of wild boar laid out like peony petals)",
    type: FoodType.niku,
    noteUk: "Червоно-білі шматки дикого кабана, викладені пелюстками піонії в гарячому місо — їжа гірських сіл, поки ведмідь засинає у барлозі.",
    noteEn: "Red-and-white wild boar laid in petal shapes in hot miso broth — mountain-village food while the bear sleeps in its hollow den.",
  ),
  63: FoodPairing(
    japanese: "鮭の塩焼き",
    romaji: "shake no shio-yaki",
    nameUk: "Шаке-но шіо-які (солений лосось, гриль на прямому вогні)",
    nameEn: "Shake no shio-yaki (salt-cured salmon grilled directly over flame)",
    type: FoodType.sakana,
    noteUk: "Солений лосось, обвуглений по краях — тіло риби, що пробилася крізь зимову течію туди, де колись вилупилося.",
    noteEn: "A salt-cured salmon, edges charred — the body of a fish that has fought up through winter water to where it was once a roe.",
  ),
  64: FoodPairing(
    japanese: "冬至かぼちゃ",
    romaji: "tōji-kabocha",
    nameUk: "Тодзі-кабоча (тушкований гарбуз з адзукі на день зимового сонцестояння)",
    nameEn: "Tōji-kabocha (kabocha squash simmered with adzuki on the winter solstice)",
    type: FoodType.yasai,
    noteUk: "Помаранчевий шматок гарбуза з темно-червоною адзукі — сонячний колір, який ставлять на стіл саме того дня, коли сонце стоїть найкоротше.",
    noteEn: "An orange piece of kabocha against dark adzuki — a sun-colour set on the table the very day the sun keeps its shortest stand.",
  ),
  65: FoodPairing(
    japanese: "鹿肉の鍋",
    romaji: "shika-niku no nabe",
    nameUk: "Шіка-ніку-но набе (гарячий горщик із олениною та гірськими овочами)",
    nameEn: "Shika-niku no nabe (venison hot pot with mountain vegetables)",
    type: FoodType.niku,
    noteUk: "Темна оленина у місо-горщику з листям перили — глибока, наче той ліс, у якому самець оленя якраз скидає торішні роги.",
    noteEn: "Dark venison in a miso pot with shiso — deep as the forest in which a stag has only just dropped last year's antlers.",
  ),
  66: FoodPairing(
    japanese: "お雑煮",
    romaji: "ozōni",
    nameUk: "Одзоні (новорічний суп з мочі, овочами і даші)",
    nameEn: "Ozōni (New Year mochi soup, varied region by region)",
    type: FoodType.shirumono,
    noteUk: "Новорічний суп з округлим мочі і зеленими паростками — перший подих року, поданий гарячим, поки під снігом росте молода пшениця.",
    noteEn: "A New Year soup of round mochi and green shoots — the year's first breath served hot, while wheat shoots push up under the snow.",
  ),
  67: FoodPairing(
    japanese: "七草粥",
    romaji: "nanakusa-gayu",
    nameUk: "Нанакуса-ґаю (рисова каша з сімома весняними травами, сьомого січня)",
    nameEn: "Nanakusa-gayu (rice porridge with the seven spring herbs, eaten on January 7)",
    type: FoodType.gohan,
    noteUk: "Білий рис, повільно зварений із сімома дикими травами — пісна, тиха страва на сьоме січня, щоб шлунок відпочив після свят.",
    noteEn: "White rice slowly simmered with seven wild herbs — a quiet, lean dish on the seventh day, to let the stomach recover from the feast.",
  ),
  68: FoodPairing(
    japanese: "甘酒",
    romaji: "amazake",
    nameUk: "Амадзаке (солодкий настій з ферментованого рису, ледь алкогольний)",
    nameEn: "Amazake (sweet, lightly fermented rice drink, served warm)",
    type: FoodType.nomimono,
    noteUk: "Гаряча біла чаша з амадзаке гріє долоні — солодке тепло, що тільки-тільки виникає, як перший підземний струмок, який починає рухатися.",
    noteEn: "A hot white bowl of amazake warms the hands — a sweetness barely awake, like the first underground spring beginning to move.",
  ),
  69: FoodPairing(
    japanese: "鏡開き",
    romaji: "kagami-biraki / zenzai",
    nameUk: "Каґамі-біракі / дзензай (солодке адзукі з шматочками новорічного мочі)",
    nameEn: "Kagami-biraki / zenzai (sweet adzuki soup with pieces of New Year's mochi)",
    type: FoodType.wagashi,
    noteUk: "Розтріскане новорічне мочі, опущене у солодке адзукі — крик далекого фазана з чагарника наче закликає вже відкрити дзеркало року.",
    noteEn: "Cracked New Year's mochi dropped into sweet adzuki — the call of a distant pheasant in the brush, urging the year's mirror to be opened.",
  ),
  70: FoodPairing(
    japanese: "蕗の薹味噌",
    romaji: "fukinotō-miso",
    nameUk: "Фукіното-місо (паста з місо і пасерованих бруньок білокопитника)",
    nameEn: "Fukinotō-miso (miso paste pounded with sautéed butterbur buds)",
    type: FoodType.hozon,
    noteUk: "Темна гіркувата паста з бруньок білокопитника — її кладуть на гарячий рис, наче кладуть першу зелену крапку посеред білого поля.",
    noteEn: "A dark, bitter paste of butterbur buds spooned onto hot rice — like setting down the first green dot in the middle of a white field.",
  ),
  71: FoodPairing(
    japanese: "おしるこ",
    romaji: "oshiruko",
    nameUk: "Ошіруко (солодкий суп з адзукі та обвугленим мочі)",
    nameEn: "Oshiruko (sweet adzuki soup with grilled mochi)",
    type: FoodType.wagashi,
    noteUk: "Червона солодка пюрешка з адзукі і шматком обвугленого мочі — гаряче в долонях, поки на гірському струмку лід стає у саму свою товщу.",
    noteEn: "A red, lightly sweet adzuki pool with one piece of charred mochi — held warm in the hands while the mountain streams freeze deepest.",
  ),
  72: FoodPairing(
    japanese: "福豆",
    romaji: "fukumame",
    nameUk: "Фукумаме (смажена соя для розкидання на Сецубун)",
    nameEn: "Fukumame (roasted soybeans thrown to drive out demons on Setsubun)",
    type: FoodType.hozon,
    noteUk: "Жменя смаженої сої — її кидають за поріг з вигуком «они-ва-сото» саме того вечора, коли курки ще раз починають нести яйця.",
    noteEn: "A handful of roasted soybeans flung over the threshold with \"oni-wa-soto\" — on the same evening hens begin laying their eggs again.",
  ),
};

FoodPairing? foodForKo(int koIndex) => seasonalFoods[koIndex];
